# k8s-mysql.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops-mysql57
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/devops-mysql57
  uid: 864efd9c-c7c9-4f18-965d-f1a229515247
  resourceVersion: '54856200'
  generation: 1
  creationTimestamp: '2020-07-08T08:03:51Z'
  labels:
    appgroup: ''
  annotations:
    deployment.kubernetes.io/revision: '1'
    description: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-mysql57
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devops-mysql57
      annotations:
        metrics.alpha.kubernetes.io/custom-endpoints: '[{"api":"","path":"","port":"","names":""}]'
    spec:
      volumes:
        - name: vol-159419526623132606
          hostPath:
            path: /DevProjectFiles
            type: ''
      containers:
        - name: container-0
          image: 'g127/mysql:5.7'
          env:
            - name: PAAS_APP_NAME
              value: devops-mysql57
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: 07d230b5a4800fec2ff2c017e53da2ba
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: vol-159419526623132606
              mountPath: /var/lib/mysql
              subPath: ws-data/mysql
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
        - name: default-secret
      affinity: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      dnsConfig:
        options:
          - name: timeout
            value: ''
          - name: ndots
            value: '5'
          - name: single-request-reopen
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-07-08T08:03:52Z'
      lastTransitionTime: '2020-07-08T08:03:52Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-07-08T08:03:52Z'
      lastTransitionTime: '2020-07-08T08:03:52Z'
      reason: ReplicaSetUpdated
      message: ReplicaSet "devops-mysql57-b464795cc" is progressing.
