credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "gitlab-token"
              secret: ${GITLAB_PERSONAL_ACCESS_TOKEN:-"123456"}
              description: "GitLab personal access token"
          # git plugin 连接只支持 usernamePassword 和 证书两种方式
          - usernamePassword:
              scope: GLOBAL
              id: "1"
              username: "jenkins"
              # 密码待修改
              password: "jenkins123"
#
jenkins:
  numExecutors: 4
  scmCheckoutRetryCount: 2
  mode: NORMAL
  quietPeriod: 5
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  globalNodeProperties:
  - envVars:
      env:
      - key: "gitlabUrl"
        value: "http://localhost:9080"
      # - key: "jenkinsUrl"
      #   value: "http://localhost:8080"
  #
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"

  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  remotingSecurity:
    enabled: true
  slaveAgentPort: ${SLAVE_AGENT_PORT:-50000}
#
unclassified:
  # location:
  #   url: "http://localhost:8080/"
  # globalLibraries:
  #   libraries:
  #   - name: "awesome-lib"
  #   - defaultVersion: "master"
  #     implicit: true
  #     name: "awesome-lib"
  #     retriever:
  #       modernSCM:
  #         scm:
  #           git:
  #             id: "awesome-lib"
  #             remote: "https://github.com/jenkins-infra/pipeline-library.git"
  #             traits:
  #             - cloneOptionTrait:
  #                 extension:
  #                   depth: 1
  #                   noTags: true
  #                   shallow: true
#

jobs:
  - script: >
      job('seed') {
        quietPeriod(0)
        concurrentBuild(false)
        logRotator {
          numToKeep(10)
        }
        steps {
          shell('echo job dsl!')
        }
      }

