FROM postgres:10-alpine

# env
ENV TZ=Asia/Shanghai \
    TSINGHUA_MIRROR=https://mirrors.tuna.tsinghua.edu.cn \
    POSTGRES_USER=root \
    POSTGRES_PASSWORD=root \
    POSTGRES_DB=postgres \
    PGDATA=/var/lib/postgresql/data/pgdata

# volume
VOLUME /var/lib/postgresql/data/pgdata



