FROM nacos/nacos-server:latest

ENV PREFER_HOST_MODE=hostname \
    MODE=standalone \
    SPRING_DATASOURCE_PLATFORM=mysql \
    MYSQL_SERVICE_HOST=devops-mysql57.default.svc.cluster.local \
    MYSQL_SERVICE_DB_NAME=nacos \
    MYSQL_SERVICE_PORT=3306 \
    MYSQL_SERVICE_USER=dev \
    MYSQL_SERVICE_PASSWORD=NpSmC2gV \
    END=end

