# nginx-docker-compose.yml 
# use host network
###
#
# 
# docker run \
#   --name web-nginx \
#   --restart=unless-stopped  \
#   -v ~/DevProjectFiles/ws-conf/nginx/:/usr/local/openresty/nginx/conf/ \
#   -v ~/DevProjectFiles/ws-root/:/DevProjectFiles/ws-root/ \
#   -v ~/tmp/logs/nginx:/usr/local/openresty/nginx/logs \
#   --privileged \
#   --net=host \
#   -d guogang1984/alpine-openresty:alpine-fat
#
# docker stop web-nginx && docker rm  web-nginx
###
version: "2"
services:
  nginx:
    image: guogang1984/alpine-openresty:alpine-fat
    container_name: web-nginx
    restart: unless-stopped
    #ports:
    #  - '80:8080'
    volumes:
      # fixed UTC+8 localtime problem
      - ~/DevProjectFiles/ws-conf/alpine/etc/localtime:/etc/localtime:ro
      # nginx conf default path
      - ~/DevProjectFiles/ws-conf/nginx/:/usr/local/openresty/nginx/conf/
      # nginx root  default path
      - ~/DevProjectFiles/ws-root/:/DevProjectFiles/ws-root/
      # nginx logs  default path     
      - ~/tmp/logs/nginx:/usr/local/openresty/nginx/logs
    network_mode: "host"
