# username/password   nacos/nacos
# docker run \
#   --name nacos \
#   -e PREFER_HOST_MODE=hostname \
#   -e MODE=standalone \
#   -e SPRING_DATASOURCE_PLATFORM=mysql \
#   -e MYSQL_SERVICE_HOST=mysql \
#   -e MYSQL_SERVICE_DB_NAME=nacos \
#   -e MYSQL_SERVICE_PORT=3306 \
#   -e MYSQL_SERVICE_USER=root \
#   -e MYSQL_SERVICE_PASSWORD=root \
#   -p 8848:8848 \
#   -p 9555:9555 \
#   --net=topflames-net \
#   --link db-mysql:mysql \
#   -d nacos/nacos-server:latest

# 创建数据库
# https://github.com/alibaba/nacos/blob/master/distribution/conf/nacos-mysql.sql
# 访问地址
# http://nacos.topflames.com:8848/nacos/index.html
version: '2'
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    restart: unless-stopped
    hostname: 'nacos.topflames.com'
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
    ports:
      - '8848:8848'
      - '9555:9555'
    external_links:
      - db-mysql:mysql
    volumes:
      - ~/tmp/logs/nacos-standalone-logs:/home/nacos/logs
    networks:
      - app-net
networks:
  app-net:
    external:
      name: app-net

