# docker-jenkins.yml 
# rm -rf ~/DevProjectFiles/ws-conf/jenkins/*
# This may also be found at: /var/jenkins_home/secrets/initialAdminPassword
# cat ~/DevProjectFiles/ws-conf/jenkins/secrets/initialAdminPassword
#
# docker run \
#   --user root \
#   --hostname jenkins \
#   --name jenkins \
#   -e TZ='Asia/Shanghai' \
#   -p 9000:8080 \
#   -p 50000:50000 \
#   --link gitlab:dev.topflames.com \
#   -v ~/DevProjectFiles/ws-conf/alpine/etc/localtime:/etc/localtime:ro  \
#   -v ~/DevProjectFiles/ws-conf/jenkins:/var/jenkins_home \
#   --privileged \
#   --net=topflames-net \
#   --rm \
#   -d jenkins/jenkins:lts-alpine
#
# docker stop jenkins && docker rm  -fv jenkins
# docker rm -fv jenkins
#
version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:lts-alpine'
    container_name: jenkins
    restart: unless-stopped
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - ~/DevProjectFiles/ws-conf/alpine/etc/localtime:/etc/localtime:ro
      - ~/DevProjectFiles/ws-conf/jenkins:/var/jenkins_home
      #- /bin/docker:/usr/bin/docker
      #- /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:8080"
      - "50000:50000"
    external_links:
        - gitlab:dev.topflames.com
    networks:
      - topflames-net
networks:
  topflames-net:
    external:
      name: topflames-net