# docker-jenkins.yml 
# rm -rf ~/DevProjectFiles/ws-conf/jenkins/*
# This may also be found at: /var/jenkins_home/secrets/initialAdminPassword
# cat ~/DevProjectFiles/ws-conf/jenkins/secrets/initialAdminPassword
#
# docker run \
#   --user root \
#   --hostname ci.topflames.com \
#   --name jenkins-ci \
#   --restart=unless-stopped  \
#   -e TZ='Asia/Shanghai' \
#   -p 8080:8080 \
#   -p 50000:50000 \
#   --link gitlab:dev.topflames.com \
#   -v ~/DevProjectFiles/ws-conf/alpine/etc/localtime:/etc/localtime:ro  \
#   -v ~/DevProjectFiles/ws-conf/jenkins:/var/jenkins_home \
#   --privileged \
#   --net=app-net \
#   -d jenkins/jenkins:lts-alpine
#
# docker stop jenkins && docker rm  -fv jenkins
# docker rm -fv jenkins
#
# http://<jenkins-url>/script
# Jenkins.instance.pluginManager.plugins.each{ 
#   plugin -> 
#     println ("${plugin.getDisplayName()} (${plugin.getShortName()}): ${plugin.getVersion()}")
# }
#
# docker run \
#       --user jenkins \
#       --hostname ci.topflames.com \
#       --name jenkins-casc \
#       --restart=unless-stopped  \
#       -e SLAVE_AGENT_PORT=32082 \
#       -p 8080:8080 \
#       -p 32082:32082 \
#       -v $HOME/.ssh:/var/jenkins_home/.ssh:ro \
#       -v $HOME/DevProjectFiles/SupportLibrary/.m2/repository:/var/jenkins_home/.m2/repository:rw \
#       -v $HOME/DevProjectFiles/ws-data/jenkins-casc:/var/jenkins_home \
#       -v /var/run/docker.sock:/var/run/docker.sock \
#       --group-add=$(stat -c %g /var/run/docker.sock) \
#       --privileged \
#       -d g127/jenkins-casc

version: '2'
services:
  jenkins:
    image: 'g127/jenkins-casc'
    container_name: jenkins-casc
    hostname: 'ci.topflames.com'
    restart: unless-stopped
    environment:
      SLAVE_AGENT_PORT: 32082
    volumes:
      - home/dev/.ssh:/var/jenkins_home/.ssh:ro
      - home/dev/DevProjectFiles/SupportLibrary/.m2/repository:/var/jenkins_home/.m2/repository:rw
      - home/dev/DevProjectFiles/ws-data/jenkins-casc:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    external_links:
        - gitlab:dev.topflames.com
    networks:
      - app-net
networks:
  app-net:
    external:
      name: app-net