# docker run \
#   --hostname redis3 \
#   --name db-redis3-1 \
#   --restart=unless-stopped  \
#   -p 127.0.0.1:6379:6379 \
#   -v ~/DevProjectFiles/ws-conf/alpine/etc/localtime:/etc/localtime:ro \
#   -v ~/DevProjectFiles/ws-data/redis3-1:/data \
#   --privileged \
#   --net=topflames-net \
#   -d redis:3.2.12-alpine
#
# docker stop db-redis3-1 && docker rm  db-redis3-1
version: "2"
services:
  redis3:
    image: redis:3.2.12-alpine
    container_name: db-redis3-1
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ~/DevProjectFiles/ws-conf/alpine/etc/localtime:/etc/localtime:ro
      - ~/DevProjectFiles/ws-data/redis3-1:/data
    networks:
      - topflames-net
networks:
  topflames-net:
    external:
      name: topflames-net
