# docker-gitlab-ce.yml 
# backup
# docker exec -it <your container name> gitlab-rake gitlab:backup:create
# docker exec -it 098e2817edac gitlab-rake gitlab:backup:create
version: '2'
services:
    gitlab:
      image: 'twang2218/gitlab-ce-zh:11.0.1'
      container_name: gitlab
      restart: unless-stopped
      hostname: 'dev.topflames.com'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_BACKUP_SCHEDULE: 'daily'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://dev.topflames.com'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          # 需要配置到 gitlab.rb 中的配置可以在这里配置，每个配置一行，注意缩进。
          # 比如下面的电子邮件的配置：
          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
          gitlab_rails['smtp_port'] = 25
          gitlab_rails['smtp_user_name'] = "support@topflames.com"
          gitlab_rails['smtp_password'] = "Tf123456"
          gitlab_rails['smtp_domain'] = "exmail.qq.com"
          gitlab_rails['smtp_authentication'] = :plain
          gitlab_rails['smtp_enable_starttls_auto'] = true
          gitlab_rails['smtp_tls'] = false
          # gitlab_email_enabled
          gitlab_rails['gitlab_email_enabled'] = true
          gitlab_rails['gitlab_email_from'] = 'support@topflames.com'
          gitlab_rails['gitlab_email_display_name'] = '驼峰支持'
          gitlab_rails['gitlab_email_reply_to'] = 'support@topflames.com'
          # backup
          # gitlab_rails['manage_backup_path'] = true
          # gitlab_rails['backup_path'] = '/var/opt/gitlab/backups'
      ports:
        - '80:80'
        #- '443:443'
        #- '22:22'
      volumes:
        - ~/DevProjectFiles/ws-conf/gitlabcezh:/etc/gitlab
        - ~/DevProjectFiles/ws-data/gitlabcezh:/var/opt/gitlab
        - ~/tmp/logs/gitlab:/var/log/gitlab
      networks:
        - topflames-net
networks:
  topflames-net:
    external:
      name: topflames-net