# --------------------------------------------------------
#
# 
# docker run \
#   --name web-dev1 \
#   --restart=unless-stopped  \
#   -e TZ='Asia/Shanghai' \
#   -e CATALINA_TMPDIR='/tmp/java/tmp' \
#   -e JAVA_OPTS=' -Djava.io.tmpdir=/tmp/java/tmp -Djava.security.egd=file:/dev/./urandom -Duser.timezone=GMT+08 -server -Xms1024m -Xmx2048m -XX:PermSize=256m -XX:MaxPermSize=512m ' \
#   -p 127.0.0.1:28081:8080 \
#   --link db-mysql:mysql \
#   --link db-redis3-2:redis \
#   -v ~/DevProjectFiles/ws-conf/tomcat8/context.xml.redis.docker:/opt/tomcat/conf/context.xml \
#   -v ~/DevProjectFiles/ws-conf/tomcat8/localhost28081:/opt/tomcat/conf/Catalina/localhost \
#   -v ~/DevProjectFiles/ws-root/:/DevProjectFiles/ws-root/ \
#   -v ~/tmp/logs/web-dev1:/tmp/logs \
#   -v ~/tmp/logs/web-dev1:/tmp/java \
#   -v ~/tmp/logs/web-dev1:/logs \
#   --privileged \
#   --net=app-net \
#   -d g127/java \
#   /opt/tomcat/bin/catalina.sh run
# --------------------------------------------------------
version: "2"
services:
  tomcat-dev01:
    image: 'g127/java'
    container_name: web-dev1
    restart: unless-stopped
    environment:
      TZ: 'Asia/Shanghai'
      CATALINA_TMPDIR : '/tmp/java/tmp'
      CATALINA_APPBASE : '/DevProjectFiles/ws-root/webapps-28081'
      JAVA_OPTS : ' -Djava.io.tmpdir=/tmp/java/tmp -Djava.security.egd=file:/dev/./urandom -Duser.timezone=GMT+08 -server -Xms1024m -Xmx2048m -XX:PermSize=256m -XX:MaxPermSize=512m '
    ports:
      - '127.0.0.1:28081:8080'
    external_links:
      - db-mysql:mysql
      - db-redis3-2:redis3
    volumes:
      - ~/DevProjectFiles/ws-conf/tomcat8/context.xml.redis:/opt/tomcat/conf/context.xml
      - ~/DevProjectFiles/ws-conf/tomcat8/localhost28081:/opt/tomcat/conf/Catalina/localhost
      - ~/DevProjectFiles/ws-root/:/DevProjectFiles/ws-root/
      - ~/tmp/logs/web-dev1:/tmp/logs
      - ~/tmp/logs/web-dev1:/tmp/java
      - ~/tmp/logs/web-dev1:/logs
    command: "/opt/tomcat/bin/catalina.sh run"
    networks:
      - app-net
networks:
  app-net:
    external:
      name: app-net