# --------------------------------------------------------
# docker pull mongo:4.2
# docker run \
#   --hostname mongo \
#   --name db-mongo \
#   --restart=unless-stopped  \
#   -e MONGO_INITDB_ROOT_USERNAME=root \
#   -e MONGO_INITDB_ROOT_PASSWORD=root \
#   -p 27017:27017 \
#   -v /etc/localtime:/etc/localtime:ro \
#   -v /home/dev/DevProjectFiles/ws-data/mongo:/data \
#   --privileged \
#   --net=app-net \
#   -d mongo:4.2
# --------------------------------------------------------
version: "2"
services:
  mongo:
    image: 'mongo:4.2'
    container_name: db-mongo
    restart: unless-stopped
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/DevProjectFiles/ws-data/mongo:/data
    networks:
      - app-net
networks:
  app-net:
    external:
      name: app-net
