version: "2"
services:
  redis3:
    image: redis:3.0.7-alpine
    container_name: db-redis3
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ~/DevProjectFiles/ws-conf/alpine/etc/localtime:/etc/localtime:ro
      - ~/DevProjectFiles/ws-data/redis3:/data
    networks:
      - topflames-net
  mysql:
    image: 'mysql:5.6'
    container_name: db-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/DevProjectFiles/ws-conf/mysql:/etc/mysql/conf.d
      - ~/DevProjectFiles/ws-data/mysql:/var/lib/mysql
      - ~/DevProjectFiles/ws-back:/DevProjectFiles/ws-back
    networks:
      - topflames-net
networks:
  topflames-net:
    external:
      name: topflames-net
