# nginx-docker-compose.yml 
# use host network
version: "2"
services:
  nodejs:
    image: dockette/nodejs:v8
    container_name: web-nodejs
    ports:
      - '7300:7300'
    volumes:
      # fixed UTC+8 localtime problem
      - ~/DevProjectFiles/ws-conf/alpine/etc/localtime:/etc/localtime:ro
      - ~/DevProjectFiles/ws-java:/ws-java
    working_dir: /ws-java/easy-mock
#    command: [ "sh", "-c", "npm --registry https://registry.npm.taobao.org install && npm run build && npm run start" ]
    command: [ "sh", "-c", "npm install && npm run build && npm run start" ]
    networks:
      - app-net
networks:
  app-net:
    external:
      name: app-net
