# ( docker rm -fv redis3 || /bin/true ) && docker run \
#   --hostname redis3 \
#   --name redis3 \
#   --restart=unless-stopped  \
#   -p 127.0.0.1:6379:6379 \
#   -v ~/DevProjectFiles/ws-conf/alpine/etc/localtime:/etc/localtime:ro \
#   -v ~/DevProjectFiles/ws-data/redis3-1:/data \
#   --privileged \
#   --net=app-net \
#   -d redis:5.0-alpine
#
# docker stop db-redis3-1 && docker rm  db-redis3-1
version: "2"
services:
  redis3:
    image: redis:5.0-alpine
    # image: redis:3.2.12-alpine
    # image: redis:6.0.9-alpine
    container_name: db-redis3-1
    # hostname: devops-redis32.default.svc.cluster.local
    restart: unless-stopped
    ports:
#      - '127.0.0.1:6379:6379'
      - '127.0.0.1:6379:6379'
    volumes:
      - ~/DevProjectFiles/ws-conf/alpine/etc/localtime:/etc/localtime:ro
      - ~/DevProjectFiles/ws-data/redis3-1:/data
    networks:
      - app-net
#   redis3-2:
#     image: redis:5.0-alpine
#     container_name: db-redis3-2
#     restart: unless-stopped
#     ports:
# #      - '127.0.0.1:6380:6379'
#       - '6380:6379'
#     volumes:
#       - ~/DevProjectFiles/ws-conf/alpine/etc/localtime:/etc/localtime:ro
#       - ~/DevProjectFiles/ws-data/redis3-2:/data
#     networks:
#       - app-net
networks:
  app-net:
    external:
      name: app-net
