# docker-gitlab-ce.yml 
# backup 因操作时间较长，进入到容器中操作
# docker exec -it gitlab /bin/bash
# 备份 停掉数据连接服务
# gitlab-ctl stop unicorn
# gitlab-ctl stop sidekiq
# 开始备份
# gitlab-rake gitlab:backup:create
# ls -l /var/opt/gitlab/backups
# 恢复
# 注：1、到底那个是备份编号？ --- _gitlab之前的部分都是；
#    2、644默认权限。
# gitlab-rake gitlab:backup:restore BACKUP=备份编号
# 查看恢复状态：
# gitlab-rake gitlab:check SANITIZE=true
# 重启服务
# gitlab-ctl start unicorn
# gitlab-ctl start sidekiq
# 或
# gitlab-ctl restart
# 关于忘记管理员密码的重置方法
# https://docs.gitlab.com/ce/security/reset_root_password.html
# api 库
# https://github.com/gitlab4j/gitlab4j-api
# 官方仓库
# https://hub.docker.com/r/gitlab/gitlab-ce
# --------------------------------------------------------
#
# mkdir -p ~/DevProjectFiles/ws-conf/gitlab
# mkdir -p ~/DevProjectFiles/ws-data/gitlab
# mkdir -p ~/tmp/logs/gitlab
#
# docker run \
#   --hostname dev.topflames.com \
#   --name gitlab \
#   --restart=unless-stopped  \
#   -e TZ='Asia/Shanghai' \
#   -e GITLAB_BACKUP_SCHEDULE='daily' \
#   -e GITLAB_BACKUP_TIME='01:00' \
#   -e GITLAB_OMNIBUS_CONFIG="external_url 'http://dev.topflames.com'; gitlab_rails['gitlab_shell_ssh_port'] = 9022; gitlab_rails['time_zone'] = 'Asia/Shanghai';  gitlab_rails['smtp_enable'] = true; gitlab_rails['smtp_address'] = 'smtp.exmail.qq.com'; gitlab_rails['smtp_port'] = 25; gitlab_rails['smtp_user_name'] = 'support@topflames.com'; gitlab_rails['smtp_password'] = 'Tf123456'; gitlab_rails['smtp_domain'] = 'exmail.qq.com'; gitlab_rails['smtp_authentication'] = :plain; gitlab_rails['smtp_enable_starttls_auto'] = true; gitlab_rails['smtp_tls'] = false;  gitlab_rails['gitlab_email_enabled'] = true; gitlab_rails['gitlab_email_from'] = 'support@topflames.com'; gitlab_rails['gitlab_email_display_name'] = '驼峰支持'; gitlab_rails['gitlab_email_reply_to'] = 'support@topflames.com';" \
#   -p 80:80 \
#   -p 9022:22 \
#   --link jenkins-ci:ci.topflames.com \
#   -v ~/DevProjectFiles/ws-conf/gitlab:/etc/gitlab \
#   -v ~/DevProjectFiles/ws-data/gitlab:/var/opt/gitlab \
#   -v ~/tmp/logs/gitlab:/var/log/gitlab \
#   --privileged \
#   -d gitlab/gitlab-ce:11.11.8-ce.0
#
# --------------------------------------------------------
version: '2'
services:
      image: 'gitlab/gitlab-ce:11.11.8-ce.0'
      container_name: gitlab
      restart: unless-stopped
      hostname: 'dev.topflames.com'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_BACKUP_SCHEDULE: 'daily'
        GITLAB_BACKUP_TIME: '01:00'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://dev.topflames.com'
          # 80 端口改listen_port 和 external_url 也要改
          nginx['listen_port'] = 80;
          # 22 端口改这里也要改
          gitlab_rails['gitlab_shell_ssh_port'] = 9022
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          # 需要配置到 gitlab.rb 中的配置可以在这里配置，每个配置一行，注意缩进。
          # 比如下面的电子邮件的配置：
          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = 'smtp.exmail.qq.com'
          gitlab_rails['smtp_port'] = 25
          gitlab_rails['smtp_user_name'] = 'support@topflames.com'
          gitlab_rails['smtp_password'] = 'Tf123456'
          gitlab_rails['smtp_domain'] = 'exmail.qq.com'
          gitlab_rails['smtp_authentication'] = :plain
          gitlab_rails['smtp_enable_starttls_auto'] = true
          gitlab_rails['smtp_tls'] = false
          # gitlab_email_enabled
          gitlab_rails['gitlab_email_enabled'] = true
          gitlab_rails['gitlab_email_from'] = 'support@topflames.com'
          gitlab_rails['gitlab_email_display_name'] = '驼峰支持'
          gitlab_rails['gitlab_email_reply_to'] = 'support@topflames.com'
          # backup
          # gitlab_rails['manage_backup_path'] = true
          # gitlab_rails['backup_path'] = '/var/opt/gitlab/backups'
      ports:
        - '80:80'
        #- '443:443'
        - '9022:22'
      external_links:
        - jenkins-ci:ci.topflames.com
      volumes:
        - ~/DevProjectFiles/ws-conf/gitlab:/etc/gitlab
        - ~/DevProjectFiles/ws-data/gitlab:/var/opt/gitlab
        - ~/tmp/logs/gitlab:/var/log/gitlab
      networks:
        - app-net
networks:
  app-net:
    external:
      name: app-net