# docker-jenkins.yml 
# rm -rf ~/DevProjectFiles/ws-conf/jenkins/*
# This may also be found at: /var/jenkins_home/secrets/initialAdminPassword
# cat ~/DevProjectFiles/ws-conf/jenkins/secrets/initialAdminPassword
#
#
# docker stop jenkins && docker rm  -fv jenkins
# docker rm -fv jenkins
#
# http://<jenkins-url>/script
# Jenkins.instance.pluginManager.plugins.each{ 
#   plugin -> 
#     println ("${plugin.getDisplayName()} (${plugin.getShortName()}): ${plugin.getVersion()}")
# }
#
# ( docker rm -fv jenkins || /bin/true ) && docker run \
#     --user jenkins \
#     --hostname ci.topflames.com \
#     --name jenkins \
#     --restart=unless-stopped  \
#     -e SLAVE_AGENT_PORT=32082 \
#     -p 32080:8080 \
#     -p 32082:32082 \
#     -v $HOME/.ssh:/var/jenkins_home/.ssh:ro \
#     -v $HOME/DevProjectFiles/SupportLibrary/.m2/repository:/var/enkins_home/.m2/repository:rw \
#     -v $HOME/DevProjectFiles/SupportLibrary/.m2/repository:/DevProjectFilesSupportLibrary/.m2/repository:rw \
#     -v $HOME/DevProjectFiles/ws-data/jenkins:/var/jenkins_home \
#     -v /var/run/docker.sock:/var/run/docker.sock \
#     --group-add=$(stat -c %g /var/run/docker.sock) \
#     --link gitlab:dev.topflames.com  \
#     --link gitlab:dev.tf360.top  \
#     --privileged   \
#     --net=app-net  \
#     -d g127/jenkins:lts-devops
#
#  手工添加docker执行权限,使用root登录后，增加用户组后，必需重启
#  docker exec -it -u root jenkins bash
#  addgroup -g $(stat -c %g /var/run/docker.sock) docker && addgroup jenkins docker
#  docker stop jenkins
#  docker start jenkins

version: '2'
services:
  jenkins:
    image: 'g127/jenkins:lts-devops'
    container_name: jenkins
    privileged: true
    user: jenkins
    hostname: 'ci.tf360.top'
    restart: unless-stopped
    environment:
      SLAVE_AGENT_PORT: 32082
    volumes:
      - /home/dev/.ssh:/var/jenkins_home/.ssh:ro
      - /home/dev/DevProjectFiles/SupportLibrary/.m2/repository:/var/jenkins_home/.m2/repository:rw
      - /home/dev/DevProjectFiles/SupportLibrary/.m2/repository:/DevProjectFiles/SupportLibrary/.m2/repository
      - /home/dev/DevProjectFiles/ws-data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "32080:8080"
      - "32082:32082"
      # - "50000:50000"
    external_links:
        - gitlab:dev.topflames.com
        - gitlab:dev.tf360.top
    networks:
      - app-net
networks:
  app-net:
    external:
      name: app-net